// Code generated by ml/train.py. DO NOT EDIT.
package main

// Predict returns the predicted class (0, 1, or 2) using the embedded Random Forest model.
func Predict(features []float64) int {
	// Accumulators for probabilities across all estimators
	var p0, p1, p2 float64

	// Tree 0
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 1
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 2
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 3
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 4
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 5
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 6
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 7
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 8
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 9
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 10
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 11
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 12
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 13
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 14
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 15
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 16
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 17
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 18
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 19
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 20
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 21
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 22
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 23
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 24
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 25
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 26
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 27
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 28
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 29
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 30
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 31
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 32
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 33
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 34
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 35
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 36
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 37
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 38
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 39
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 40
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 41
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 42
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 43
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 44
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 45
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 46
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 47
	{
		var t0, t1, t2 float64
		if features[2] <= 57.500000 {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		} else {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 48
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Tree 49
	{
		var t0, t1, t2 float64
		if features[3] <= 0.500000 {
			t0 = 1.000000
			t1 = 0.000000
			t2 = 0.000000
		} else {
			t0 = 0.000000
			t1 = 0.000000
			t2 = 1.000000
		}
		p0 += t0
		p1 += t1
		p2 += t2
	}

	// Argmax class selection
	if p0 >= p1 && p0 >= p2 {
		return 0
	} else if p1 >= p0 && p1 >= p2 {
		return 1
	} else {
		return 2
	}
}
